[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LibSerialPort = "32d10148-a048-4782-a230-5cc9375b6574"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[targets]
test = ["Dates", "GLMakie", "LibSerialPort", "Printf", "Sockets", "Statistics"]

[compat]
julia = "1.6" # Or your preferred minimum Julia version
GLMakie = "0.9" # Specify versions for your dependencies
LibSerialPort = "0.2"
# Add other dependencies like Sockets, Printf, Dates, Statistics if specific versions are needed

name = "ThermalESP32"
uuid = "..." # Generate a UUID using `using UUIDs; uuid4()` in Julia REPL
authors = ["Your Name <your.email@example.com>"] # Replace with your details
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LibSerialPort = "32d10148-a048-4782-a230-5cc9375b6574"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
